# Please refer https://aka.ms/HTTPSinContainer on how to setup an https developer certificate for your ASP .NET Core service.

version: '3.4'

services:
  telegrammicroservice:
    image: telegrammicroservice
    build:
      context: .
      dockerfile: src/TelegramMicroservice/Dockerfile
    ports:
      - 5001:5001
